modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="arcane_heart"
version="1.0.0"
displayName="Arcane Heart"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="OracleOfDarkness, SuperBenji9 MCreator"

[[dependencies.arcane_heart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.arcane_heart]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arcane_heart]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcane_heart]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

